# Generated by Django 6.0.1 on 2026-01-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('preferences', models.TextField()),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Dish_Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.TextField(null=True)),
                ('display_order', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dish_categories',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=150)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=3, max_digits=10)),
                ('min_stock_threshold', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('display_order', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('cooking_time_min', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('allergens', models.CharField(max_length=255)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.dish_categories')),
            ],
            options={
                'db_table': 'dishes',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(max_length=50)),
                ('delivery_address', models.TextField()),
                ('customer_phone', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.customers')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_required', models.DecimalField(decimal_places=3, max_digits=7)),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.dishes')),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.ingredients')),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
    ]
